### ISSUE TITLE
Where is development occuring now ?

### ISSUE THREAD

**Issue by gotcha** [webtrix/moonocolor#5]
http://ckeditor.com/addon/moonocolor lead me to here.
That page mentions versions 4.5.1 and 1.4.1 but they have not been tagged here.

And no commits have been pushed since Sep 9, 2013

**Comment by webtrix** [comment]
Hi, there isn't really any development anymore to be honest.  The code really hasn't changed anymore over the past few years.  We just made sure that the skin works in all the versions of CKEditor, but to do this I didn't need to make any changes in the code.  This skin is actually only a change in the icons, nothing more.

**Comment by gotcha** [comment]
Nevertheless, the files in versions 1.4.1 and 4.5.1 have differences. Is there a public repository somewhere which can be used to track the history ?

**Comment by webtrix** [comment]
Not really.  Why do you need this?

**Comment by gotcha** [comment]
I am automating the integration of Moono Color into `collective.ckeditor` for Plone CMS.

A git repo with tags would be easier than downloading zip files...

**Comment by webtrix** [comment]
Sorry.. can't help you with that.

**Comment by gotcha** [comment]
I managed with downloads.

Thanks for your answers
